export default () => ({
  rects: [
    {
      width: 300,
      height: 100,
      top: 20,
      left: 20,
      draggable: true,
      resizable: true,
      minw: 100,
      minh: 30,
      axis: 'both',
      parentLim: true,
      snapToGrid: true,
      aspectRatio: false,
      zIndex: 1,
      color: '#EF9A9A',
      active: false,
      class: 'shadow-sm',
    },
    {
      width: 300,
      height: 100,
      top: 40,
      left: 40,
      draggable: true,
      resizable: true,
      minw: 10,
      minh: 10,
      axis: 'both',
      parentLim: true,
      snapToGrid: true,
      aspectRatio: false,
      zIndex: 2,
      color: '#E6C27A',
      active: false,
      class: 'shadow',
    },
    {
      width: 300,
      height: 100,
      top: 60,
      left: 60,
      draggable: true,
      resizable: true,
      minw: 100,
      minh: 30,
      axis: 'both',
      parentLim: true,
      snapToGrid: true,
      aspectRatio: false,
      zIndex: 3,
      color: '#AED581',
      active: false,
    },
    {
      width: 300,
      height: 100,
      top: 80,
      left: 80,
      draggable: true,
      resizable: true,
      minw: 100,
      minh: 30,
      axis: 'both',
      parentLim: true,
      snapToGrid: true,
      aspectRatio: false,
      zIndex: 4,
      color: '#81D4FA',
      active: false,
    },
    {
      width: 300,
      height: 100,
      top: 100,
      left: 100,
      draggable: true,
      resizable: true,
      minw: 100,
      minh: 30,
      axis: 'both',
      parentLim: true,
      snapToGrid: true,
      aspectRatio: false,
      zIndex: 5,
      color: '#fae881',
      active: false,
    },
  ],
})
